### PR TITLE
Proposed disclaimer

### PR DESCRIPTION
**Pull request by ekr**

### CODE REVIEW

**Review by martinthomson — APPROVED** [review]
I had something less than this, but this works.

**Comment by ekr** [comment]
What would you trim off?

**Comment by martinthomson** [comment]
All I came up with was "this isn't widely deployed".  Yours is better.

**Review by seanturner — APPROVED** [review]
I think this is a wroth while addition in the spirit of truth in advertising.

**Comment by ekr** [comment]
We'll need AD sign off, I expect.

**Pull request merged**
